CREATE TABLE FLOODGATE_API (
    ID VARCHAR2(256) NOT NULL PRIMARY KEY,
    DATA CLOB,
    CREATE_DATE TIMESTAMP,
    CREATE_ID VARCHAR2(32),
    MODIFY_DATE TIMESTAMP,
    MODIFY_ID VARCHAR2(32),
    ACTIVE CHAR(1),
    TEST CHAR(1),
    NOTE VARCHAR2(246)
);

CREATE TABLE FLOODGATE_DATASOURCE (
    ID VARCHAR2(256) NOT NULL PRIMARY KEY,
    DATA CLOB,
    CREATE_DATE TIMESTAMP,
    CREATE_ID VARCHAR2(32),
    MODIFY_DATE TIMESTAMP,
    MODIFY_ID VARCHAR2(32),
    ACTIVE CHAR(1),
    TEST CHAR(1),
    NOTE VARCHAR2(256)
);

CREATE TABLE FLOODGATE_FLOW (
    ID VARCHAR2(256) NOT NULL PRIMARY KEY,
    DATA CLOB,
    CREATE_DATE TIMESTAMP,
    CREATE_ID VARCHAR2(32),
    MODIFY_DATE TIMESTAMP,
    MODIFY_ID VARCHAR2(32),
    ACTIVE CHAR(1),
    TEST CHAR(1),
    NOTE VARCHAR2(245)
);

CREATE TABLE FLOODGATE_API_HISTORY (
    ID VARCHAR2(128) NOT NULL PRIMARY KEY,
    API_ID VARCHAR2(256),
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    LOG VARCHAR2(256),
    FULL_LOG CLOB
);

CREATE TABLE FLOODGATE_FLOW_HISTORY (
    ID VARCHAR2(128) NOT NULL PRIMARY KEY,
    FLOW_ID VARCHAR2(256),
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    LOG VARCHAR2(256),
    FULL_LOG CLOB
);

CREATE TABLE FLOODGATE_META_HISTORY (
    TABLE_NAME VARCHAR2(128),
    ID VARCHAR2(128),
    DATA CLOB,
    CREATE_DATE TIMESTAMP,
    CREATE_ID VARCHAR2(32),
    MODIFY_DATE TIMESTAMP,
    MODIFY_ID VARCHAR2(32),
    ACTIVE CHAR(1),
    TEST CHAR(1),
    NOTE VARCHAR2(256)
);
