CREATE TABLE IF NOT EXISTS FG_API (
    ID VARCHAR(255) PRIMARY KEY,
    DATA CLOB
);

CREATE TABLE IF NOT EXISTS FG_FLOW (
    ID VARCHAR(255) PRIMARY KEY,
    DATA CLOB
);

CREATE TABLE IF NOT EXISTS FG_DATASOURCE (
    ID VARCHAR(255) PRIMARY KEY,
    DATA CLOB
);

CREATE TABLE IF NOT EXISTS FG_TEMPLATE (
    ID VARCHAR(255) PRIMARY KEY,
    DATA CLOB
);

CREATE TABLE IF NOT EXISTS FG_LOG_API (
    ID VARCHAR(255) PRIMARY KEY,
    DATA CLOB
);

CREATE TABLE IF NOT EXISTS FG_LOG_FLOW (
    ID VARCHAR(255) PRIMARY KEY,
    DATA CLOB
);
