-- oracle

CREATE TABLE API (
    ID varchar2(128) NOT NULL PRIMARY KEY,
    DATA NCLOB
)

CREATE TABLE DATASOURCE (
    ID varchar2(128) NOT NULL PRIMARY KEY,
    DATA NCLOB
)

CREATE TABLE FLOW (
    ID varchar2(128) NOT NULL PRIMARY KEY,
    DATA NCLOB
)

CREATE TABLE API_HISTORY (
    ID varchar2(128) NOT NULL PRIMARY KEY,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    LOG varchar2(128),
    FULL_LOG NCLOB
)

-- PostgreSQL

CREATE TABLE API (
    ID varchar(128) PRIMARY KEY,
    DATA TEXT
)

CREATE TABLE DATASOURCE (
    ID varchar(128) PRIMARY KEY,
    DATA TEXT
)

CREATE TABLE FLOW (
    ID varchar(128) PRIMARY KEY,
    DATA TEXT
)

CREATE TABLE API_HISTORY (
    ID varchar(128) PRIMARY KEY,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    LOG varchar(4000),
    FULL_LOG TEXT
)
